apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  template:
    spec:
      securityContext: null
      containers:
        - name: controller
          securityContext: null
