apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.50.100-10.0.50.200
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.50.201-10.0.50.250
  autoAssign: false
