apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../app
  - ../../drivers
  - scc.yaml

patches:
  - path: secret-patch.yaml
    target:
      kind: Secret
      name: democratic-csi-driver-config

images:
  - name: docker.io/democraticcsi/democratic-csi
    newName: docker.io/skaterdurf/democratic-csi
    newTag: latest
