kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: democratic-csi-privileged-scc
  namespace: democratic-csi
subjects:
  - kind: ServiceAccount
    name: democratic-csi-node-sa
    namespace: democratic-csi
  - kind: ServiceAccount
    name: democratic-csi-controller-sa
    namespace: democratic-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
