apiVersion: v1
kind: Service
metadata:
  name: steam-cache-dns
  annotations:
    metallb.universe.tf/allow-shared-ip: "steam-cache"
spec:
  selector:
    app: steam-cache-dns
  externalTrafficPolicy: Cluster
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns-udp
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
  type: LoadBalancer
  loadBalancerIP: 10.0.50.201
