apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-cache-data
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
