apiVersion: v1
kind: Service
metadata:
  name: steam-cache
  annotations:
    metallb.universe.tf/allow-shared-ip: "steam-cache"
spec:
  selector:
    app: steam-cache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
  loadBalancerIP: 10.0.50.201
  externalTrafficPolicy: Cluster
