apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: org.democratic-csi.freenas-nfs
allowVolumeExpansion: true
parameters:
  fsType: nfs
