apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  secretName: harbor-tls
  dnsNames:
    - harbor.lab.garrettholland.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
