allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
  - "*"
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  name: harbor-anyuid
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seccompProfiles:
  - "*"
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:harbor:default
  - system:serviceaccount:harbor:harbor
  - system:serviceaccount:harbor:core
  - system:serviceaccount:harbor:jobservice
  - system:serviceaccount:harbor:registry
  - system:serviceaccount:harbor:portal
  - system:serviceaccount:harbor:database
  - system:serviceaccount:harbor:redis
  - system:serviceaccount:harbor:trivy
